### ISSUE TITLE
Ongoing issue with EOModel.createPrototypeCache()

### ISSUE THREAD

**Issue by paulhoadley** [hprange/wounit#40]
I'm opening a new ticket here to distinguish it from #35 which is _probably the same issue_, but it wouldn't seem to have anything to do with partial entities (at least directly).

As reported in #35, the fix to `ERXModelGroup` seemed to clear up the problem for me, _until it didn't_. I'm still seeing it intermittently, though only running in Eclipse. It _seems_ to be solid on Jenkins, though maybe I haven't run it enough times to see it. Further, sometimes it will fail on _one test_ in a class (usually the first) and then proceed to pass on all the others. Here's a stack trace from my `RoleTest` class, testing an entity called `Role` which is _not_ a partial entity:

```
com.webobjects.foundation.NSForwardException [java.lang.reflect.InvocationTargetException] null:java.lang.reflect.InvocationTargetException
	at com.webobjects.foundation._NSUtilities._explainInstantiationException(_NSUtilities.java:626)
	at com.webobjects.foundation._NSUtilities.instantiateObjectWithConstructor(_NSUtilities.java:665)
	at com.webobjects.eoaccess.EOEntityClassDescription.createInstanceWithEditingContext(EOEntityClassDescription.java:242)
	at com.webobjects.eoaccess.EOUtilities.createAndInsertInstance(EOUtilities.java:861)
	at com.wounit.rules.AbstractEditingContextRule$UnderTestFacade.create(AbstractEditingContextRule.java:72)
	at com.wounit.rules.AnnotationProcessor.createEOForType(AnnotationProcessor.java:49)
	at com.wounit.rules.AnnotationProcessor.initializeObject(AnnotationProcessor.java:172)
	at com.wounit.rules.AnnotationProcessor.process(AnnotationProcessor.java:205)
	at com.wounit.rules.AbstractEditingContextRule.before(AbstractEditingContextRule.java:182)
	at com.wounit.rules.MockEditingContext.before(MockEditingContext.java:147)
	at com.wounit.rules.AbstractEditingContextRule$1.evaluate(AbstractEditingContextRule.java:162)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.webobjects.foundation._NSUtilities.instantiateObjectWithConstructor(_NSUtilities.java:659)
	... 24 more
Caused by: java.lang.NullPointerException
	at com.webobjects.eoaccess.EOModel.createPrototypeCache(EOModel.java:631)
	at com.webobjects.eoaccess.EOModel.prototypeAttributeNamed(EOModel.java:699)
	at com.webobjects.eoaccess.ERXModel.prototypeAttributeNamed(ERXModel.java:290)
	at com.webobjects.eoaccess.EOAttribute.<init>(EOAttribute.java:998)
	at com.webobjects.eoaccess.EOEntity.attributes(EOEntity.java:816)
	at com.webobjects.eoaccess.EOEntity.attributeNamed(EOEntity.java:789)
	at com.webobjects.eoaccess.EOEntity.classProperties(EOEntity.java:1098)
	at com.webobjects.eoaccess.EOEntity._propertyDictionaryInitializer(EOEntity.java:3321)
	at com.webobjects.eoaccess.EOEntity._newDictionaryForProperties(EOEntity.java:3667)
	at com.webobjects.eoaccess.EOEntityClassDescription._newDictionaryForProperties(EOEntityClassDescription.java:88)
	at com.webobjects.eocontrol.EOGenericRecord.__setClassDescription(EOGenericRecord.java:111)
	at com.webobjects.eocontrol.EOGenericRecord.__setClassDescription(EOGenericRecord.java:100)
	at com.webobjects.eocontrol.EOGenericRecord.<init>(EOGenericRecord.java:73)
	at er.extensions.eof.ERXGenericRecord.<init>(ERXGenericRecord.java:103)
	at net.logicsquad.access.model._Role.<init>(_Role.java:15)
	at net.logicsquad.access.model.Role.<init>(Role.java:15)
	... 29 more
```

I'm seeing the same telltale console output here when it fails:

```
- Entity classDescription is not ERXEntityClassDescription: Privilege
- Entity classDescription is not ERXEntityClassDescription: Role
- Entity classDescription is not ERXEntityClassDescription: RolePrivilege
```

and _not_ when it passes.

Henrique, I am more than happy to send you a small test framework that exhibits the issue. Let me know if you want it.

**Comment by paulhoadley** [comment]
Hi Henrique,

Just started a new project, using WOUnit for testing from the ground up. I'm still seeing this issue. Have you got _anything_ I could try to help diagnose the problem?

**Comment by paulhoadley** [comment]
I got perilously close to closing this ticket. For unrelated reasons, I set up another Jenkins build server, and started running some WOUnit tests that had otherwise been failing on Jenkins—no problems. I built it from scratch, added the latest Wonder frameworks, made sure everything was pristine. But then, sure enough, as I transferred some older projects over (just via configuration, no code or build products—everything re-fetched from version control), the `InvocationTargetException` issue started reappearing, though, believe it or not, not necessarily in the same tests. It doesn't seem deterministic (thought it's repeatable between runs of the same project on the same build server).

So close, yet still so far away.

**Comment by paulhoadley** [comment]
I may have finally solved this, or at least worked around it. I'm reasonably sure this issue is related to #35, where we saw multiple attempts to load the same model, and a fix was applied to `ERXModelGroup` to use a set instead of an array. Despite this, I was still seeing this kind of thing when tests were failing as described above:

```
    [junit] - The model 'Ident' (path: file:/var/lib/jenkins/workspace/LSAccess/Resources/Ident.eomodeld) cannot be added to model group <EOModelGroup (("Ident", "file:/var/lib/jenkins/workspace/LSAccess/Resources/Ident.eomodeld"), ("Control", "file:/var/lib/jenkins/workspace/LSAccess/Resources/Control.eomodeld"), ("erprototypes", "file:/var/lib/jenkins/workspace/LSAccess/Root/Library/Frameworks/ERPrototypes.framework/Resources/erprototypes.eomodeld"))> because it already contains a model with that name.
    [junit] - The model 'Control' (path: file:/var/lib/jenkins/workspace/LSAccess/Resources/Control.eomodeld) cannot be added to model group <EOModelGroup (("Ident", "file:/var/lib/jenkins/workspace/LSAccess/Resources/Ident.eomodeld"), ("Control", "file:/var/lib/jenkins/workspace/LSAccess/Resources/Control.eomodeld"), ("erprototypes", "file:/var/lib/jenkins/workspace/LSAccess/Root/Library/Frameworks/ERPrototypes.framework/Resources/erprototypes.eomodeld"))> because it already contains a model with that name.
```

Reading that first line closely, I noted that the `Resources` directory in the project workspace was being searched, despite setting `dir="${dest.dir}/${project.name}.framework"` in `build.xml`. Suspecting this was the cause of the collisions, I temporarily moved `Resources` out of the way and _all tests passed_.

As a slightly clunky workaround, then, I'm using the `chmod` task either side of `junit` in `build.xml` to make `Resources` unreadable, so it's only the built framework in `dist` that's now being searched for models. This seems to be sufficient to fix the consistent failures I was seeing when running these tests on a Jenkins buildserver. As a final observation, I note that _application_ projects don't seem to exhibit this problem, and it's not clear why. I'm calling the tests with an otherwise identical `junit` task, just pointing the `dir` attribute at the `.woa` bundle.

**Comment by paulhoadley** [comment]
I'm happy to close this issue. The "chmod hack" is sufficient for my purposes. It would be interesting to know why we're getting the duplicate model loading in some situations, but if no one else is seeing it, I'm not sure we'll get to the bottom of it any time soon.
